name: Build AppImage
on: 
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libfuse2
        version: 1.0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build AppImage
      id: build-appimage
      run: |
        ./build.sh
    - uses: mukunku/tag-exists-action@v1.1.0
      id: checkTag
      with: 
        tag: 'v{{ env.CONAN_VERSION }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload AppImage
      if: steps.checkTag.outputs.exists == 'false'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: v${{ env.CONAN_VERSION }}
        title: "Conan v${{ env.CONAN_VERSION }}"
        files: conan-${{ env.CONAN_VERSION }}-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
